version: '3'

services:
  backend:
    container_name: backend-api
    image: node:18.18-alpine
    restart: always
    tty: true
    env_file:
      - .env
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE_NAME}