import Head from 'next/head'
import { Text } from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import { parseCookies } from 'nookies'
// import { useForm } from 'react-hook-form'
// import useAuth from '@/hooks/useAuth'
// import { ISignUpCredentials } from '@/types'

export default function Signup() {
  // const {
  //   register,
  //   handleSubmit,
  //   watch,
  //   formState: { errors }
  // } = useForm<ISignUpCredentials>()
  // const { signIn } = useAuth()
  // async function onSubmitHandler(data: ISignUpCredentials) {
  //   try {
  //     await signIn(data)
  //   } catch (error: any) {
  //     console.error(error.response?.data)
  //   }
  // }
  return (
    <>
      <Head>
        <title>signup Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>signup</Text>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx: any) => {
  const cookies = parseCookies(ctx)
  if (cookies['backendtoken']) {
    return {
      redirect: {
        destination: '/',
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}
